-- Create table for quiz questions
CREATE TABLE IF NOT EXISTS quiz_questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_answer CHAR(1) NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL
);

-- Insert 75 US Citizenship Test Questions
INSERT INTO quiz_questions (question, option_a, option_b, option_c, option_d, correct_answer, category, difficulty) VALUES
('What is the supreme law of the land?', 'The Bill of Rights', 'The Constitution', 'The Declaration of Independence', 'Federal law', 'B', 'citizenship', 'easy'),
('What does the Constitution do?', 'Creates the military', 'Sets up the government and protects basic rights', 'Establishes trade policies', 'Controls immigration', 'B', 'citizenship', 'easy'),
('The idea of self-government is in the first three words of the Constitution. What are these words?', 'Life, Liberty, Pursuit', 'We the People', 'In God We Trust', 'United We Stand', 'B', 'citizenship', 'easy'),
('What do we call the first ten amendments to the Constitution?', 'The Bill of Rights', 'The Founding Principles', 'The Constitutional Framework', 'The Basic Laws', 'A', 'citizenship', 'easy'),
('What is one right or freedom from the First Amendment?', 'The right to bear arms', 'Freedom of speech', 'The right to vote', 'Protection from searches', 'B', 'citizenship', 'easy'),
('How many amendments does the Constitution have?', 'Twenty-five', 'Thirty', 'Twenty-seven', 'Twenty-two', 'C', 'citizenship', 'medium'),
('What did the Declaration of Independence do?', 'Created the Constitution', 'Announced our independence from Great Britain', 'Established the Bill of Rights', 'Founded the Supreme Court', 'B', 'citizenship', 'easy'),
('What are two rights in the Declaration of Independence?', 'Freedom and justice', 'Life and liberty', 'Peace and prosperity', 'Safety and security', 'B', 'citizenship', 'easy'),
('What is freedom of religion?', 'You must practice Christianity', 'You can practice any religion or not practice a religion', 'You must attend church weekly', 'You can only practice approved religions', 'B', 'citizenship', 'easy'),
('What is the economic system in the United States?', 'Socialist economy', 'Communist economy', 'Capitalist economy', 'Feudal economy', 'C', 'citizenship', 'easy'),
('Name one branch of government.', 'The Congress', 'The Cabinet', 'The Senate', 'The House', 'A', 'citizenship', 'easy'),
('What stops one branch of government from becoming too powerful?', 'The Constitution', 'Checks and balances', 'The Supreme Court', 'The President', 'B', 'citizenship', 'medium'),
('Who is in charge of the executive branch?', 'The Congress', 'The Supreme Court', 'The President', 'The Cabinet', 'C', 'citizenship', 'easy'),
('Who makes federal laws?', 'The President', 'The Supreme Court', 'Congress', 'The Cabinet', 'C', 'citizenship', 'easy'),
('What are the two parts of the U.S. Congress?', 'The Senate and House of Representatives', 'The House and Cabinet', 'The Senate and Supreme Court', 'The Executive and Judicial', 'A', 'citizenship', 'easy'),
('How many U.S. Senators are there?', 'Fifty', 'One hundred', 'Four hundred thirty-five', 'Two hundred', 'B', 'citizenship', 'easy'),
('We elect a U.S. Senator for how many years?', 'Two', 'Four', 'Six', 'Eight', 'C', 'citizenship', 'medium'),
('The House of Representatives has how many voting members?', 'One hundred', 'Two hundred', 'Four hundred thirty-five', 'Five hundred', 'C', 'citizenship', 'medium'),
('We elect a U.S. Representative for how many years?', 'Two', 'Four', 'Six', 'Eight', 'A', 'citizenship', 'easy'),
('We elect a President for how many years?', 'Two', 'Four', 'Six', 'Eight', 'B', 'citizenship', 'easy'),
('In what month do we vote for President?', 'October', 'November', 'December', 'January', 'B', 'citizenship', 'easy'),
('If the President can no longer serve, who becomes President?', 'The Speaker of the House', 'The Secretary of State', 'The Vice President', 'The Chief Justice', 'C', 'citizenship', 'easy'),
('If both the President and Vice President can no longer serve, who becomes President?', 'The Secretary of State', 'The Speaker of the House', 'The Chief Justice', 'The Secretary of Defense', 'B', 'citizenship', 'medium'),
('Who is the Commander in Chief of the military?', 'The Secretary of Defense', 'The Joint Chiefs of Staff', 'The President', 'The Vice President', 'C', 'citizenship', 'easy'),
('Who signs bills to become laws?', 'The Vice President', 'The President', 'The Speaker of the House', 'The Chief Justice', 'B', 'citizenship', 'easy'),
('Who vetoes bills?', 'Congress', 'The President', 'The Supreme Court', 'The Cabinet', 'B', 'citizenship', 'easy'),
('What does the President''s Cabinet do?', 'Makes laws', 'Interprets laws', 'Advises the President', 'Commands the military', 'C', 'citizenship', 'easy'),
('What does the judicial branch do?', 'Makes laws', 'Reviews laws', 'Enforces laws', 'Vetoes laws', 'B', 'citizenship', 'easy'),
('What is the highest court in the United States?', 'The Federal Court', 'The Supreme Court', 'The District Court', 'The Appeals Court', 'B', 'citizenship', 'easy'),
('Under our Constitution, what is one power of the federal government?', 'Provide education', 'Issue driver''s licenses', 'To print money', 'Provide police protection', 'C', 'citizenship', 'medium'),
('Under our Constitution, what is one power of the states?', 'Print money', 'Declare war', 'Provide schooling and education', 'Make treaties', 'C', 'citizenship', 'medium'),
('What are the two major political parties in the United States?', 'Republican and Libertarian', 'Democratic and Republican', 'Democratic and Green', 'Republican and Independent', 'B', 'citizenship', 'easy'),
('There are four amendments about who can vote. Describe one of them.', 'You must own property to vote', 'Citizens eighteen and older can vote', 'Only men can vote', 'You must pay taxes to vote', 'B', 'citizenship', 'medium'),
('What is one responsibility that is only for United States citizens?', 'Pay taxes', 'Obey the law', 'Serve on a jury', 'Get a driver''s license', 'C', 'citizenship', 'medium'),
('Name one right only for United States citizens.', 'Freedom of speech', 'Vote in a federal election', 'Freedom of religion', 'Right to a fair trial', 'B', 'citizenship', 'medium'),
('What do we show loyalty to when we say the Pledge of Allegiance?', 'The government', 'The President', 'The United States and the flag', 'The Constitution', 'C', 'citizenship', 'easy'),
('How old do citizens have to be to vote for President?', 'Sixteen', 'Eighteen', 'Twenty-one', 'Twenty-five', 'B', 'citizenship', 'easy'),
('When is the last day you can send in federal income tax forms?', 'March 15', 'April 15', 'May 15', 'June 15', 'B', 'citizenship', 'easy'),
('When must all men register for the Selective Service?', 'At age sixteen', 'At age eighteen', 'At age twenty-one', 'At age twenty-five', 'B', 'citizenship', 'medium'),
('What is one reason colonists came to America?', 'To find gold', 'For religious freedom', 'To conquer land', 'To establish monarchy', 'B', 'citizenship', 'easy'),
('Who lived in America before the Europeans arrived?', 'The Spanish', 'American Indians', 'The French', 'The British', 'B', 'citizenship', 'easy'),
('What group of people was taken to America and sold as slaves?', 'Europeans', 'Africans', 'Asians', 'Native Americans', 'B', 'citizenship', 'easy'),
('Why did the colonists fight the British?', 'To expand territory', 'Because of high taxes', 'To establish trade', 'To find resources', 'B', 'citizenship', 'easy'),
('Who wrote the Declaration of Independence?', 'George Washington', 'Benjamin Franklin', 'Thomas Jefferson', 'John Adams', 'C', 'citizenship', 'easy'),
('When was the Declaration of Independence adopted?', 'July 4, 1775', 'July 4, 1776', 'July 4, 1777', 'July 4, 1778', 'B', 'citizenship', 'easy'),
('Name three of the original 13 states.', 'California, Texas, Florida', 'New York, Pennsylvania, Virginia', 'Ohio, Indiana, Illinois', 'Alabama, Mississippi, Louisiana', 'B', 'citizenship', 'medium'),
('What happened at the Constitutional Convention?', 'The Bill of Rights was written', 'The Constitution was written', 'The Declaration was signed', 'The Revolutionary War began', 'B', 'citizenship', 'medium'),
('When was the Constitution written?', '1776', '1787', '1791', '1804', 'B', 'citizenship', 'medium'),
('Name one of the writers of the Federalist Papers.', 'George Washington', 'James Madison', 'Thomas Jefferson', 'Benjamin Franklin', 'B', 'citizenship', 'medium'),
('Who is the "Father of Our Country"?', 'Thomas Jefferson', 'Benjamin Franklin', 'George Washington', 'John Adams', 'C', 'citizenship', 'easy'),
('Who was the first President?', 'John Adams', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'C', 'citizenship', 'easy'),
('What territory did the United States buy from France in 1803?', 'The Florida Territory', 'The Louisiana Territory', 'The Texas Territory', 'The Oregon Territory', 'B', 'citizenship', 'medium'),
('Name one war fought by the United States in the 1800s.', 'World War I', 'The Civil War', 'World War II', 'The Korean War', 'B', 'citizenship', 'easy'),
('Name the U.S. war between the North and the South.', 'The Revolutionary War', 'The War of 1812', 'The Civil War', 'The Mexican-American War', 'C', 'citizenship', 'easy'),
('What was one important thing that Abraham Lincoln did?', 'Founded the Republican Party', 'Freed the slaves', 'Wrote the Constitution', 'Won the Revolutionary War', 'B', 'citizenship', 'easy'),
('What did the Emancipation Proclamation do?', 'Ended the Civil War', 'Freed the slaves', 'Created the Constitution', 'Started the Revolutionary War', 'B', 'citizenship', 'easy'),
('What did Susan B. Anthony do?', 'Was the first female President', 'Fought for women''s rights', 'Founded the Red Cross', 'Was a Civil War nurse', 'B', 'citizenship', 'medium'),
('Name one war fought by the United States in the 1900s.', 'The Civil War', 'The Revolutionary War', 'World War II', 'The War of 1812', 'C', 'citizenship', 'easy'),
('Who was President during World War I?', 'Theodore Roosevelt', 'Woodrow Wilson', 'Franklin Roosevelt', 'William Taft', 'B', 'citizenship', 'medium'),
('Who was President during the Great Depression and World War II?', 'Theodore Roosevelt', 'Harry Truman', 'Franklin Roosevelt', 'Dwight Eisenhower', 'C', 'citizenship', 'medium'),
('Who did the United States fight in World War II?', 'Russia, China, and France', 'Japan, Germany, and Italy', 'Britain, France, and Spain', 'Mexico, Canada, and Cuba', 'B', 'citizenship', 'medium'),
('During the Cold War, what was the main concern of the United States?', 'Fascism', 'Capitalism', 'Communism', 'Socialism', 'C', 'citizenship', 'medium'),
('What movement tried to end racial discrimination?', 'The labor movement', 'The civil rights movement', 'The women''s movement', 'The peace movement', 'B', 'citizenship', 'easy'),
('What did Martin Luther King, Jr. do?', 'Was a President', 'Fought for civil rights', 'Was a Supreme Court Justice', 'Founded the NAACP', 'B', 'citizenship', 'easy'),
('What major event happened on September 11, 2001?', 'A hurricane hit', 'Terrorists attacked the United States', 'An earthquake occurred', 'A war began', 'B', 'citizenship', 'easy'),
('Name one of the two longest rivers in the United States.', 'Colorado River', 'Mississippi River', 'Hudson River', 'Columbia River', 'B', 'citizenship', 'medium'),
('What ocean is on the West Coast of the United States?', 'Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'C', 'citizenship', 'easy'),
('What ocean is on the East Coast of the United States?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'B', 'citizenship', 'easy'),
('Name one U.S. territory.', 'Hawaii', 'Alaska', 'Puerto Rico', 'California', 'C', 'citizenship', 'medium'),
('Name one state that borders Canada.', 'California', 'Texas', 'Washington', 'Florida', 'C', 'citizenship', 'medium'),
('Name one state that borders Mexico.', 'Oregon', 'Colorado', 'California', 'Nevada', 'C', 'citizenship', 'medium'),
('What is the capital of the United States?', 'New York City', 'Philadelphia', 'Washington, D.C.', 'Boston', 'C', 'citizenship', 'easy'),
('Where is the Statue of Liberty?', 'Washington, D.C.', 'New York Harbor', 'Philadelphia', 'Boston Harbor', 'B', 'citizenship', 'easy'),
('Why does the flag have 13 stripes?', 'For the 13 colonies', 'For the 13 amendments', 'For 13 founding fathers', 'For 13 years of war', 'A', 'citizenship', 'easy'),
('Why does the flag have 50 stars?', 'For 50 years of independence', 'For one star for each state', 'For 50 founding fathers', 'For 50 amendments', 'B', 'citizenship', 'easy'),
('What is the name of the national anthem?', 'America the Beautiful', 'God Bless America', 'The Star-Spangled Banner', 'My Country ''Tis of Thee', 'C', 'citizenship', 'easy'),
('When do we celebrate Independence Day?', 'July 3', 'July 4', 'July 5', 'August 4', 'B', 'citizenship', 'easy'),
('Name two national U.S. holidays.', 'Valentine''s Day and Halloween', 'Independence Day and Thanksgiving', 'Easter and Mother''s Day', 'St. Patrick''s Day and Earth Day', 'B', 'citizenship', 'easy'),

-- Insert 25 Current Politics Questions (More Difficult)
('According to current policy in 2025, what percentage tariff has the administration threatened to impose on Russia if no Ukraine peace deal is reached?', '50%', '75%', '100%', '125%', 'C', 'current_politics', 'hard'),
('What is the official name of the government efficiency initiative led by Elon Musk?', 'Government Optimization Department', 'Department of Government Efficiency (DOGE)', 'Federal Efficiency Agency', 'Bureaucratic Reform Office', 'B', 'current_politics', 'hard'),
('Which federal agencies'' data is DOGE reportedly combining to create a master database for immigration enforcement?', 'FBI and CIA only', 'IRS, Social Security, and DHS', 'DOD and State Department', 'Treasury and Commerce only', 'B', 'current_politics', 'hard'),
('What cryptocurrency initiative did the current administration establish in March 2025?', 'Federal Digital Currency', 'Strategic Bitcoin Reserve', 'Government Crypto Fund', 'National Blockchain Initiative', 'B', 'current_politics', 'hard'),
('Under the current administration''s NATO policy, who pays for U.S. weapons sent to Ukraine?', 'Ukraine directly', 'NATO allies', 'The United States exclusively', 'The European Union', 'B', 'current_politics', 'hard'),
('What is the deadline set by DOGE for the U.S. DOGE Service Temporary Organization to terminate?', 'December 31, 2025', 'January 20, 2026', 'July 4, 2026', 'December 31, 2026', 'C', 'current_politics', 'hard'),
('According to current policy, what is prohibited regarding Central Bank Digital Currencies (CBDCs)?', 'Only international transactions', 'Research and development', 'Establishment within U.S. jurisdiction', 'Private sector involvement', 'C', 'current_politics', 'hard'),
('What controversial executive order provision allows DOGE to access agency records and systems?', 'Freedom of Information Enhancement', 'Administrative Transparency Act', 'Displaces prior executive orders that might be barriers', 'Government Accountability Mandate', 'C', 'current_politics', 'hard'),
('Which data verification system has USCIS enhanced to help eliminate voter fraud according to 2025 updates?', 'REAL ID System', 'E-Verify Database', 'SAVE Program', 'NCIC Database', 'C', 'current_politics', 'hard'),
('What is the current federal debt ceiling situation creating pressure for in 2025?', 'Increased defense spending', '$2.5 trillion in spending cuts', 'New tax increases', 'Infrastructure investments', 'B', 'current_politics', 'hard'),
('Which Silicon Valley company is reportedly helping DOGE build its master database?', 'Google', 'Meta', 'Palantir', 'Microsoft', 'C', 'current_politics', 'hard'),
('What major regulatory framework is the current administration developing for digital assets?', 'Blockchain Supervision Act', 'Federal regulatory framework for stablecoins', 'Cryptocurrency Control Measures', 'Digital Asset Restriction Protocol', 'B', 'current_politics', 'hard'),
('According to current immigration enforcement policy, what type of database is being built by combining multiple federal agency data?', 'Criminal Background System', 'Tax Compliance Database', 'Master database for immigration status', 'Employment Verification System', 'C', 'current_politics', 'hard'),
('What is the current administration''s approach to the war in Ukraine regarding weapons shipments?', 'Direct U.S. funding only', 'NATO pays, U.S. provides weapons', 'European Union exclusive funding', 'United Nations coordination', 'B', 'current_politics', 'hard'),
('Which privacy law has been cited in up to fourteen lawsuits regarding DOGE''s data access?', 'HIPAA of 1996', 'Privacy Act of 1974', 'FERPA of 1974', 'COPPA of 1998', 'B', 'current_politics', 'hard'),
('What is the current status of the U.S. debt-to-GDP ratio trajectory?', 'Decreasing steadily', 'Remaining stable', 'Poised to hit record heights', 'Fluctuating unpredictably', 'C', 'current_politics', 'hard'),
('According to 2025 policy, what happens to federal employee credit cards under cost efficiency measures?', 'Unlimited usage', 'Frozen for 30 days with exceptions', 'Completely eliminated', 'Reduced spending limits', 'B', 'current_politics', 'hard'),
('What is the main concern European allies have expressed about current U.S. foreign policy?', 'Too much cooperation', 'Insufficient military support', 'Unpredictable and unreliable partnership', 'Excessive diplomatic engagement', 'C', 'current_politics', 'hard'),
('Which executive order was revoked regarding digital assets policy?', 'Executive Order 14065', 'Executive Order 14067', 'Executive Order 14069', 'Executive Order 14071', 'B', 'current_politics', 'hard'),
('What controversial practice has DOGE been accused of regarding government data?', 'Sharing with foreign entities', 'Exfiltration to private databases', 'Complete data deletion', 'Public release of classified information', 'B', 'current_politics', 'hard'),
('According to current tariff policy, what is the "reciprocal tariff" approach?', 'Matching other countries'' tariff rates', 'Eliminating all tariffs', 'Imposing uniform global rates', 'Negotiating bilateral agreements', 'A', 'current_politics', 'hard'),
('What is the current administration''s position on NATO Article 5 commitments?', 'Unconditional support', 'Conditional on "fair" treatment', 'Complete withdrawal', 'Renegotiation required', 'B', 'current_politics', 'hard'),
('Which type of federal contracts has DOGE targeted for termination to achieve cost savings?', 'Defense contracts only', 'Infrastructure projects', 'Discretionary spending contracts and grants', 'Social security payments', 'C', 'current_politics', 'hard'),
('What is the current administration''s approach to European defense spending?', 'Increase U.S. contributions', 'Require 5% of GDP spending by allies', 'Eliminate NATO funding', 'Transfer all costs to UN', 'B', 'current_politics', 'hard'),
('According to current policy, what characterizes the approach to Russia-Ukraine peace negotiations?', 'Unconditional support for Ukraine', 'Pressure through economic sanctions and tariffs', 'Military intervention', 'Complete neutrality', 'B', 'current_politics', 'hard');